import Database from 'better-sqlite3';
import path from 'path';
import { fileURLToPath } from 'url';
import bcrypt from 'bcryptjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Database file stored locally in server directory
const dbPath = path.join(__dirname, '..', 'sales_saas.db');
const db = new Database(dbPath);

// Enable Write-Ahead Logging (WAL) for high concurrency and performance
db.pragma('journal_mode = WAL');

/**
 * Initialize all required tables for the SaaS platform:
 * 1. users: Account authentication, current subscription plan, token balance
 * 2. token_ledger: Detailed audit trail of all token deductions and top-ups
 * 3. subscriptions: Active billing records (Always Free, Trial, Monthly, One-Time)
 * 4. transcripts: Video transcripts uploaded for training/grounding
 * 5. transcript_chunks: Chunked segments with vector embeddings for RAG
 * 6. reports: Saved sales objection reports generated by subscribers
 */
export function initDatabase() {
  db.exec(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      name TEXT NOT NULL,
      plan TEXT DEFAULT 'always_free', -- 'always_free', 'free_trial', 'monthly', 'one_time'
      token_balance INTEGER DEFAULT 5000, -- Base tokens for always_free tier
      trial_expires_at TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS token_ledger (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      amount INTEGER NOT NULL, -- Negative for deduction, positive for top-up/renewal
      reason TEXT NOT NULL,
      balance_after INTEGER NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS subscriptions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      plan_id TEXT NOT NULL,
      status TEXT DEFAULT 'active', -- 'active', 'canceled', 'expired'
      amount REAL DEFAULT 0,
      currency TEXT DEFAULT 'INR',
      payment_method TEXT DEFAULT 'sandbox',
      transaction_id TEXT,
      started_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      expires_at DATETIME,
      FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS transcripts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      title TEXT NOT NULL,
      video_url TEXT,
      author TEXT DEFAULT 'Manuj Bajaj',
      category TEXT DEFAULT 'Sales Coaching',
      raw_content TEXT NOT NULL,
      chunk_count INTEGER DEFAULT 0,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS transcript_chunks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      transcript_id INTEGER NOT NULL,
      chunk_index INTEGER NOT NULL,
      content TEXT NOT NULL,
      keywords TEXT, -- Extracted keywords for fast local hybrid RAG search
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(transcript_id) REFERENCES transcripts(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS reports (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      product TEXT NOT NULL,
      industry TEXT NOT NULL,
      result_json TEXT NOT NULL,
      tokens_spent INTEGER NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    );
  `);

  // Seed default Demo User if users table is empty
  const userCount = db.prepare('SELECT COUNT(*) as count FROM users').get();
  if (userCount.count === 0) {
    const salt = bcrypt.genSaltSync(10);
    const hash = bcrypt.hashSync('demo1234', salt);

    const trialEnd = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();

    const insertUser = db.prepare(`
      INSERT INTO users (email, password_hash, name, plan, token_balance, trial_expires_at)
      VALUES (?, ?, ?, ?, ?, ?)
    `);

    // Create a demo user on Free 1-Month Trial with 50,000 tokens
    const result = insertUser.run('demo@manujbajaj.com', hash, 'Demo Subscriber', 'free_trial', 50000, trialEnd);

    // Record initial token grant in ledger
    db.prepare(`
      INSERT INTO token_ledger (user_id, amount, reason, balance_after)
      VALUES (?, ?, ?, ?)
    `).run(result.lastInsertRowid, 50000, 'Initial Free 1-Month Trial Token Grant', 50000);

    console.log('✅ Demo user seeded: demo@manujbajaj.com / demo1234 with 50,000 tokens.');
  }

  // Seed core transcripts from Manuj Bajaj's methodology if transcripts table is empty
  seedInitialTranscripts();
}

/**
 * Seed foundational sales objection transcripts based on Manuj Bajaj's signature methods:
 * 1. Stab & Twist Methodology (Exposing hidden bleedings)
 * 2. 6KLH Framework (Kab-Kab, Kahan-Kahan, Kitna-Kitna)
 * 3. Handling Indian "Bhav-Taav" and Delay objections
 */
function seedInitialTranscripts() {
  const transcriptCount = db.prepare('SELECT COUNT(*) as count FROM transcripts').get();
  if (transcriptCount.count > 0) return;

  const seedLessons = [
    {
      title: "Mastering the 'Stab & Twist' Objection Handling Framework",
      video_url: "https://youtube.com/watch?v=manuj_stab_twist_mastery",
      author: "Manuj Bajaj",
      category: "Objection Handling Methodology",
      content: `In high-ticket sales, when a client says 'your price is too high' or 'budget nahi hai', amateur salespeople start offering discounts. This is fatal.
My 'Stab & Twist' framework changes the game completely:
1. The STAB: Validate their stated concern, but immediately expose the bleeding wound they already have. Show them where money is already silently draining from their business right now.
For example: 'Aap 30% discount maang rahe hain taaki aap ₹3 Lakh bacha sakein, lekin kya aapne notice kiya ki har mahine wrong inventory tracking aur delayed invoicing ki wajah se aapka ₹2.5 Lakh seedha leak ho raha hai?'
2. The TWIST: Now twist the knife by projecting the severe cost of inaction over the next 6 to 12 months.
For example: 'Agar agle 6 mahine yeh leak control nahi hua, toh ₹15 Lakh ka direct profit khatam ho jayega aur competitor market share le lega. Aaj ₹3 Lakh bachaane ke chakkar me salana ₹15 Lakh gawana sabse bada nuksaan hai!'
Always transition from the twist into a no-risk bridge offer.`
    },
    {
      title: "The 6KLH Breakdown for Indian MSME & Enterprise Buyers",
      video_url: "https://youtube.com/watch?v=manuj_6klh_breakdown",
      author: "Manuj Bajaj",
      category: "6KLH Calculation Framework",
      content: `Indian business owners and traditional promoters (Lala mindset) do not buy features. They buy cash leakage protection and immediate ROI.
To crack them, use my 6KLH formula:
- KAB-KAB (When does the leakage happen?): Pinpoint the exact recurring time triggers, such as shift handovers, monthly GST input tax credit reconciliation, month-end billing closures, or seasonal supplier checkout.
- KAHAN-KAHAN (Where does the loss occur?): Identify the specific operational points: factory dispatch gates, manual ledger entries, double-freight handling, or customer support escalations.
- KITNA-KITNA (How much rupee value is lost?): Quantify in hard Indian Rupees (₹). Never speak in vague percentages. Say: '₹1.8 Lakh per month lost in transit delays' or '₹75,000 wasted every quarter on manual re-auditing'.
When you speak in exact numbers and timeline triggers, negotiation ends because arithmetic does not negotiate.`
    },
    {
      title: "Countering 'Abhi Mandha Chal Raha Hai, Diwali / Agle Saal Dekhenge'",
      video_url: "https://youtube.com/watch?v=manuj_timing_delay_rebuttal",
      author: "Manuj Bajaj",
      category: "Timing & Delay Rebuttals",
      content: `Delay is the silent killer of deals. When a prospect says 'Market slow hai, Diwali baad dekhenge' or 'Next year budget me consider karenge', here is how you close:
1. Reframe recession as the urgency driver: 'Jab market mandha hota hai, tab toh inefficiency bardasht karna double risk hai. Bull market me galtiyan chhip jaati hain, mandhe market me jo ₹1 bachta hai vo seedha net profit me judta hai.'
2. Cost of the 4-month waiting period: 'Diwali 4 mahine door hai. In 4 mahino me leakage band nahi hogi. Har mahine ₹1 Lakh leak hoga yaani Diwali aane tak ₹4 Lakh ka cash loss pakka hai. Kya aap such me Diwali ka intezaar ₹4 Lakh gawaane ke liye kar rahe hain?'
3. The Lock-in Offer: 'Aap poora payment mat kijiye. Aaj sirf 15% booking deposit se current rate freeze kijiye aur pilot chalu kijiye taaki Diwali aane tak system profit create karna shuru kar chuke.'`
    },
    {
      title: "Handling 'Local Vendor Ya Purana Vendor Saste Me De Raha Hai'",
      video_url: "https://youtube.com/watch?v=manuj_local_vendor_objection",
      author: "Manuj Bajaj",
      category: "Competitive Rebuttals",
      content: `Clients often compare specialized enterprise solutions with cheap local freelancers or legacy vendors.
Teach your sales team:
1. Don't badmouth the local vendor. Respect them: 'Purana vendor aapke basic kaam ke liye theek tha.'
2. Expose the hidden 'Support & Scalability Tax': 'Lekin jab aapka turnover 2x hoga, kya unka single-person team compliance, cloud backup aur uptime guarantee de payega?'
3. Highlight rework cost: 'Local vendor ka code crash hone par breakdown cost per hour kitni aati hai? Hamara 99.9% uptime SLA contract certified hai with instant refund penalty clauses.'
Make them realize cheap solutions are the most expensive mistakes over a 3-year timeline.`
    }
  ];

  const insertTranscript = db.prepare(`
    INSERT INTO transcripts (title, video_url, author, category, raw_content, chunk_count)
    VALUES (?, ?, ?, ?, ?, ?)
  `);

  const insertChunk = db.prepare(`
    INSERT INTO transcript_chunks (transcript_id, chunk_index, content, keywords)
    VALUES (?, ?, ?, ?)
  `);

  for (const lesson of seedLessons) {
    const res = insertTranscript.run(
      lesson.title,
      lesson.video_url,
      lesson.author,
      lesson.category,
      lesson.content,
      1
    );

    // Extract basic keywords for hybrid RAG search
    const keywords = lesson.content
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, '')
      .split(/\s+/)
      .filter(w => w.length > 3)
      .slice(0, 30)
      .join(' ');

    insertChunk.run(res.lastInsertRowid, 0, lesson.content, keywords);
  }

  console.log(`✅ Seeded ${seedLessons.length} foundational video transcripts from Manuj Bajaj's coaching library.`);
}

export default db;
