import React, { useState } from 'react';
import { Video, Copy, Printer, Share2, Check, ArrowRight, Calculator, ChevronDown, ChevronUp } from 'lucide-react';

export default function ReportView({ report, scenario, onReset }) {
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState('objections'); // 'objections', 'questions', 'calculator'
  const [openObjection, setOpenObjection] = useState(0);

  // Calculator State
  const [dealValue, setDealValue] = useState(1000000); // ₹10 Lakh
  const [leakageRate, setLeakageRate] = useState(15); // 15% estimated monthly leakage
  const [delayMonths, setDelayMonths] = useState(4); // 4 months delay

  const monthlyLeakage = Math.round(dealValue * (leakageRate / 100));
  const totalDelayLoss = monthlyLeakage * delayMonths;
  const annualLoss = monthlyLeakage * 12;

  const formatINR = (val) => {
    if (val >= 10000000) return `₹${(val / 10000000).toFixed(2)} Crore`;
    if (val >= 100000) return `₹${(val / 100000).toFixed(2)} Lakh`;
    return `₹${val.toLocaleString('en-IN')}`;
  };

  const handleCopy = () => {
    let fullText = `*Sales Intelligence Report: ${scenario.product}*\n`;
    fullText += `Industry: ${scenario.targetIndustry}\n\n`;
    fullText += `*EXECUTIVE SUMMARY*\n${report.summary}\n\n`;
    fullText += `*TOP OBJECTIONS & STAB-TWIST REBUTTALS*\n`;

    report.objections?.forEach((cat, cIdx) => {
      fullText += `\n[${cat.category}]\n`;
      cat.items?.forEach((item, iIdx) => {
        fullText += `\nObjection: "${item.objection}"\n`;
        fullText += `🗡️ Stab: ${item.stab}\n`;
        fullText += `🌀 Twist: ${item.twist}\n`;
        if (item.six_klh_breakdown) {
          fullText += `⏱️ 6KLH: Kab=${item.six_klh_breakdown.kab_kab} | Kahan=${item.six_klh_breakdown.kahan_kahan} | Kitna=${item.six_klh_breakdown.kitna_kitna}\n`;
        }
        fullText += `🤝 Pitch: ${item.closing_offer_pitch}\n`;
      });
    });

    navigator.clipboard.writeText(fullText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleWhatsAppShare = () => {
    const topObj = report.objections?.[0]?.items?.[0]?.objection || 'Budget is too tight';
    const text = encodeURIComponent(
      `*Sales Objection Handling Strategy: ${scenario.product}*\n\n` +
      `*Key Objection:* "${topObj}"\n` +
      `*Recommended Rebuttal (Stab & Twist):* Grounded on Manuj Bajaj's 6KLH sales system.\n\n` +
      `View the complete report generated by Sales Intelligence Assistant.`
    );
    window.open(`https://api.whatsapp.com/send?text=${text}`, '_blank');
  };

  return (
    <div className="space-y-6">
      
      {/* Top Banner with Actions */}
      <div className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-8 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div>
          <div className="flex items-center gap-2 mb-1.5">
            <span className="bg-emerald-50 text-emerald-800 border border-emerald-200 text-[10px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full">
              Video Transcript Grounded
            </span>
            {report._meta?.engineSource && (
              <span className="text-slate-500 text-xs font-mono">
                Tokens Deducted: <strong className="text-slate-800 font-bold">{report._meta.tokensConsumed}</strong>
              </span>
            )}
          </div>
          <h2 className="text-xl sm:text-2xl font-black text-slate-900 tracking-tight">
            Sales Defense Dossier: <span className="text-emerald-700">{scenario.product}</span>
          </h2>
          <p className="text-xs text-slate-500 mt-1">
            Target Sector: {scenario.targetIndustry} • Ticket Size: {scenario.dealSize}
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2 sm:gap-2.5 no-print w-full md:w-auto">
          <button
            onClick={handleCopy}
            className="flex-1 sm:flex-none bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 text-xs font-semibold px-3 py-2.5 rounded-xl transition-all flex items-center justify-center gap-1.5 shadow-xs min-h-[40px]"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied!' : 'Copy'}</span>
          </button>

          <button
            onClick={handleWhatsAppShare}
            className="flex-1 sm:flex-none bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border border-emerald-200 text-xs font-bold px-3 py-2.5 rounded-xl transition-all flex items-center justify-center gap-1.5 shadow-xs min-h-[40px]"
          >
            <Share2 className="w-4 h-4 text-emerald-600" />
            <span>WhatsApp</span>
          </button>

          <button
            onClick={() => window.print()}
            className="flex-1 sm:flex-none bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 text-xs font-semibold px-3 py-2.5 rounded-xl transition-all flex items-center justify-center gap-1.5 shadow-xs min-h-[40px]"
          >
            <Printer className="w-4 h-4" />
            <span>Print PDF</span>
          </button>

          <button
            onClick={onReset}
            className="w-full sm:w-auto bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold px-5 py-2.5 rounded-xl transition-all shadow-xs min-h-[40px] flex items-center justify-center"
          >
            New Scenario
          </button>
        </div>
      </div>

      {/* RAG Knowledge Grounding Pill */}
      {report._meta?.groundedTranscripts && report._meta.groundedTranscripts.length > 0 && (
        <div className="bg-white border border-slate-200 rounded-2xl px-4 sm:px-5 py-3 sm:py-3.5 flex items-center gap-2.5 sm:gap-3 text-xs text-slate-700 shadow-xs">
          <Video className="w-4 h-4 text-emerald-600 shrink-0" />
          <div className="truncate">
            <span className="text-slate-500 font-semibold">Trained Grounding: </span>
            {report._meta.groundedTranscripts.map((title, idx) => (
              <span key={idx} className="text-emerald-800 font-semibold inline-block mr-2">
                "{title}"{idx < report._meta.groundedTranscripts.length - 1 ? ',' : ''}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Executive Summary Card */}
      <div className="bg-white border border-slate-200 rounded-2xl sm:rounded-3xl p-5 sm:p-8 shadow-sm space-y-2">
        <h3 className="text-xs font-bold uppercase tracking-wider text-emerald-800 flex items-center gap-1.5">
          <span>🧠</span> Buyer Psychology & Strategic Assessment
        </h3>
        <p className="text-xs sm:text-base text-slate-700 leading-relaxed font-normal">
          {report.summary}
        </p>
      </div>

      {/* Navigation Sub-Tabs with horizontal scroll on mobile */}
      <div className="flex border-b border-slate-200 gap-1 sm:gap-2 no-print overflow-x-auto pb-0.5 -mx-4 px-4 sm:mx-0 sm:px-0">
        <button
          onClick={() => setActiveTab('objections')}
          className={`pb-3 px-3 sm:px-4 text-xs sm:text-sm font-bold border-b-2 transition-all flex items-center gap-1.5 sm:gap-2 whitespace-nowrap shrink-0 min-h-[42px] ${
            activeTab === 'objections'
              ? 'border-emerald-600 text-emerald-700'
              : 'border-transparent text-slate-500 hover:text-slate-800'
          }`}
        >
          <span>🗡️</span> Objections & Rebuttals
        </button>

        <button
          onClick={() => setActiveTab('questions')}
          className={`pb-3 px-3 sm:px-4 text-xs sm:text-sm font-bold border-b-2 transition-all flex items-center gap-1.5 sm:gap-2 whitespace-nowrap shrink-0 min-h-[42px] ${
            activeTab === 'questions'
              ? 'border-emerald-600 text-emerald-700'
              : 'border-transparent text-slate-500 hover:text-slate-800'
          }`}
        >
          <span>❓</span> Buyer Fears
        </button>

        <button
          onClick={() => setActiveTab('calculator')}
          className={`pb-3 px-3 sm:px-4 text-xs sm:text-sm font-bold border-b-2 transition-all flex items-center gap-1.5 sm:gap-2 whitespace-nowrap shrink-0 min-h-[42px] ${
            activeTab === 'calculator'
              ? 'border-emerald-600 text-emerald-700'
              : 'border-transparent text-slate-500 hover:text-slate-800'
          }`}
        >
          <span>🧮</span> 6KLH Delay Calculator
        </button>
      </div>

      {/* TAB 1: Objections & Rebuttals */}
      {activeTab === 'objections' && (
        <div className="space-y-6">
          {report.objections?.map((cat, cIdx) => (
            <div key={cIdx} className="space-y-4">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-600" />
                <h3 className="text-sm font-black uppercase tracking-wider text-slate-800">
                  {cat.category}
                </h3>
              </div>

              <div className="space-y-4">
                {cat.items?.map((item, iIdx) => {
                  const globalIdx = cIdx * 10 + iIdx;
                  const isOpen = openObjection === globalIdx;

                  return (
                    <div 
                      key={iIdx}
                      className="bg-white border border-slate-200 hover:border-slate-300 rounded-3xl overflow-hidden transition-all shadow-xs"
                    >
                      {/* Objection Header */}
                      <button
                        type="button"
                        onClick={() => setOpenObjection(isOpen ? null : globalIdx)}
                        className="w-full text-left p-6 flex items-center justify-between gap-4 bg-slate-50/50 hover:bg-slate-100/50 transition-colors"
                      >
                        <div className="flex items-start gap-3.5">
                          <span className="bg-rose-100 text-rose-800 text-xs font-bold px-2.5 py-0.5 rounded-md mt-0.5 shrink-0">
                            Objection #{iIdx + 1}
                          </span>
                          <span className="text-base font-bold text-slate-900 italic">
                            "{item.objection}"
                          </span>
                        </div>
                        <div className="text-slate-400">
                          {isOpen ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
                        </div>
                      </button>

                      {/* Expanded Content */}
                      {isOpen && (
                        <div className="p-6 sm:p-8 space-y-6 border-t border-slate-100">
                          
                          {/* Stab Box */}
                          <div className="bg-rose-50/60 border-l-4 border-rose-500 p-5 rounded-r-2xl">
                            <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-rose-700 mb-1.5">
                              <span>🗡️</span> Step 1: The STAB (Expose Active Bleeding)
                            </div>
                            <p className="text-sm text-slate-800 leading-relaxed font-medium">
                              {item.stab}
                            </p>
                          </div>

                          {/* Twist Box */}
                          <div className="bg-amber-50/60 border-l-4 border-amber-500 p-5 rounded-r-2xl">
                            <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-amber-800 mb-1.5">
                              <span>🌀</span> Step 2: The TWIST (Cost of 6–12 Month Inaction)
                            </div>
                            <p className="text-sm text-slate-800 leading-relaxed font-medium">
                              {item.twist}
                            </p>
                          </div>

                          {/* 6KLH Breakdown */}
                          {item.six_klh_breakdown && (
                            <div className="bg-slate-50 border border-slate-200 rounded-2xl p-5">
                              <div className="text-xs font-bold uppercase tracking-wider text-slate-700 mb-3 flex items-center gap-1.5">
                                <span>⏱️</span> 6KLH Breakdown (Quantifying Hard Rupees)
                              </div>
                              <div className="grid grid-cols-1 md:grid-cols-3 gap-3.5 text-xs">
                                <div className="bg-white p-3.5 rounded-xl border border-slate-200">
                                  <span className="text-slate-400 block font-bold mb-1">KAB-KAB (When)</span>
                                  <span className="text-slate-700">{item.six_klh_breakdown.kab_kab}</span>
                                </div>
                                <div className="bg-white p-3.5 rounded-xl border border-slate-200">
                                  <span className="text-slate-400 block font-bold mb-1">KAHAN-KAHAN (Where)</span>
                                  <span className="text-slate-700">{item.six_klh_breakdown.kahan_kahan}</span>
                                </div>
                                <div className="bg-white p-3.5 rounded-xl border border-slate-200">
                                  <span className="text-emerald-700 block font-bold mb-1">KITNA-KITNA (Loss ₹)</span>
                                  <span className="text-emerald-800 font-bold">{item.six_klh_breakdown.kitna_kitna}</span>
                                </div>
                              </div>
                            </div>
                          )}

                          {/* Bridge Pitch */}
                          <div className="bg-emerald-50/70 border border-emerald-200 p-5 rounded-2xl">
                            <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-emerald-800 mb-1.5">
                              <span>🤝</span> Step 3: The Closing Bridge Offer
                            </div>
                            <p className="text-sm text-slate-800 font-medium leading-relaxed">
                              {item.closing_offer_pitch}
                            </p>
                          </div>

                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* TAB 2: Buyer Questions */}
      {activeTab === 'questions' && (
        <div className="space-y-6">
          {report.client_questions?.map((cat, cIdx) => (
            <div key={cIdx} className="space-y-4">
              <h3 className="text-sm font-black uppercase tracking-wider text-slate-800">
                {cat.category}
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                {cat.items?.map((q, qIdx) => (
                  <div key={qIdx} className="bg-white border border-slate-200 rounded-3xl p-6 shadow-xs space-y-4">
                    <div className="text-base font-bold text-slate-900 flex items-start gap-2">
                      <span className="text-emerald-600 font-mono">Q:</span>
                      <span>"{q.question}"</span>
                    </div>
                    <div className="bg-slate-50 p-4 rounded-2xl border border-slate-200 text-xs">
                      <span className="text-amber-800 font-bold block mb-1">Why High-Ticket Buyers Ask:</span>
                      <span className="text-slate-600 leading-relaxed">{q.why_they_ask}</span>
                    </div>
                    <div className="bg-emerald-50 p-4 rounded-2xl border border-emerald-200 text-xs">
                      <span className="text-emerald-800 font-bold block mb-1">Power Answer Hint:</span>
                      <span className="text-emerald-950 font-medium leading-relaxed">{q.power_answer_hint}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* TAB 3: Cost of Inaction Calculator */}
      {activeTab === 'calculator' && (
        <div className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-10 shadow-sm space-y-8">
          <div>
            <h3 className="text-xl font-bold text-slate-900 flex items-center gap-2">
              <Calculator className="w-5 h-5 text-emerald-600" />
              6KLH Live Cost of Inaction Calculator
            </h3>
            <p className="text-xs sm:text-sm text-slate-500 mt-1">
              "Numbers do not negotiate." Quantify the exact cost of prospect procrastination to shut down delay objections.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 pt-4 border-t border-slate-100">
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-2">
                Deal / System Value (₹)
              </label>
              <input
                type="number"
                value={dealValue}
                onChange={(e) => setDealValue(Number(e.target.value))}
                step="100000"
                className="w-full bg-slate-50 border border-slate-200 focus:bg-white focus:border-emerald-600 rounded-xl px-4 py-3 text-sm text-slate-900 outline-none font-mono"
              />
              <span className="text-xs text-emerald-700 font-semibold mt-1 block">
                {formatINR(dealValue)}
              </span>
            </div>

            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-2">
                Estimated Monthly Leakage (%)
              </label>
              <input
                type="range"
                min="5"
                max="40"
                value={leakageRate}
                onChange={(e) => setLeakageRate(Number(e.target.value))}
                className="w-full accent-emerald-600 mt-2"
              />
              <span className="text-xs text-slate-600 font-mono mt-1 block">
                {leakageRate}% of deal value leaking every month
              </span>
            </div>

            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-2">
                Prospect Procrastination Delay
              </label>
              <div className="flex gap-2 mt-1">
                {[3, 4, 6, 12].map((m) => (
                  <button
                    key={m}
                    type="button"
                    onClick={() => setDelayMonths(m)}
                    className={`flex-1 py-2.5 rounded-xl text-xs font-bold border transition-all ${
                      delayMonths === m
                        ? 'bg-emerald-50 text-emerald-800 border-emerald-300'
                        : 'bg-white text-slate-600 border-slate-200 hover:border-slate-300 hover:bg-slate-50'
                    }`}
                  >
                    {m} Mos
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Results Display */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 pt-4 border-t border-slate-100">
            <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200">
              <span className="text-slate-500 text-xs font-bold block mb-1">Monthly Cash Leakage</span>
              <span className="text-2xl font-black text-slate-900 font-mono">{formatINR(monthlyLeakage)}</span>
              <span className="text-[11px] text-slate-400 block mt-1">Every 30 days without system</span>
            </div>

            <div className="bg-rose-50 p-6 rounded-2xl border border-rose-200">
              <span className="text-rose-700 text-xs font-bold block mb-1">{delayMonths}-Month Delay Loss</span>
              <span className="text-2xl font-black text-rose-800 font-mono">{formatINR(totalDelayLoss)}</span>
              <span className="text-[11px] text-rose-700/80 block mt-1">Total cash lost if they postpone</span>
            </div>

            <div className="bg-emerald-50 p-6 rounded-2xl border border-emerald-200">
              <span className="text-emerald-800 text-xs font-bold block mb-1">Annual Preventable Loss</span>
              <span className="text-2xl font-black text-emerald-700 font-mono">{formatINR(annualLoss)}</span>
              <span className="text-[11px] text-emerald-800/80 block mt-1">Net profit recovered by deploying today</span>
            </div>
          </div>

          {/* Closing Talking Point */}
          <div className="p-5 bg-slate-50 rounded-2xl border border-emerald-200 text-xs text-slate-700 leading-relaxed">
            <strong className="text-emerald-800">🔥 Your Live Pitch Line:</strong> "Aap {delayMonths} mahine sochne me delay karenge, par yeh delay aapko {formatINR(totalDelayLoss)} ka cash nuksaan karwayega. Aaj hamara {formatINR(dealValue)} ka system lene se aap saal me {formatINR(annualLoss)} bacha rahe hain. Inaction is the most expensive purchase in your business!"
          </div>
        </div>
      )}

    </div>
  );
}
